
name: weathernav
description: "WeatherNav - Intelligent navigation and contextual weather."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  go_router: ^17.1.0
  maplibre_gl: ^0.25.0
  dio: ^5.4.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  lucide_icons: ^0.257.0
  google_fonts: ^8.0.2
  latlong2: ^0.9.1
  intl: ^0.20.2
  flutter_tts: ^4.0.2
  wakelock_plus: ^1.2.8
  workmanager: ^0.9.0+3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.2
  drift: ^2.16.0
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3
  hive_ce_generator: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
